config/routes.rb
Rails.application.routes.draw do
  get 'order/new'
  resources :customers
  resources :products
  resources :charges
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :email, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :items
  has_many :products, through: :items
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :items
  has_many :orders, through: :items
  validates :name, :description, :unit_price, :quantity, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]

  def index
    @customers = Customer.all
  end

  def show; end

  def new
    @customer = Customer.new
  end

  def edit; end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Cliente criado.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Cliente atualizado.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Cliente excluído.' }
      format.json { head :no_content }
    end
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :email)
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  
  def index
    @products = Product.all()
  end

  def show; end

  def new
    @product = Product.new
  end
  
  def create
      @product = Product.new(product_params)
      if @product.save
        flash[:notice] = 'Produto cadastrado'
        redirect_to products_path
      else
        render :new
      end
  end

  def edit; end

  def update
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Produto atualizado'
      redirect_to products_path
    else
      render :new
    end
  end
  
  private
  
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:id, :name, :description, :unit_price, :quantity)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Nome' %>
    <%= f.input :email, label: 'Email' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteCompra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order/new.html.erb
<h1>Order#new</h1>
<p>Find me in app/views/order/new.html.erb</p>

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= simple_form_for(@product) do |f| %>
  <div class="form-group">
    <div class="row">
      <div class="form-inputs">
        <%= f.input :name, label: 'Nome' %>
        <%= f.input :description, label: 'Descrição' %>
        <%= f.input :unit_price, label: 'Preço' %>
        <%= f.input :quantity, label: 'Quantidade' %>
      </div>
    </div>
    <div class="row">
      <%= f.button :submit, value: 'Cadastrar', class: 'btn btn-success' %>
      <%= link_to 'Voltar', products_path, class: 'btn btn-warning' %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %> </p>
<% end %>
<h1>Lista de Produtos</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Preço</th>
      <th scope="col">Quantidade</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.unit_price %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Exibir', product %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Excluir', product, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="form-actions" style="color: white">
  <%= link_to 'Novo Produto', new_product_path, class: "btn btn-info" %>
  <%= link_to 'Voltar', root_path, class: "btn btn-warning" %>
</div>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<h1>Detalhes do Produto</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Preço Unitário:</strong>
  <%= @product.unit_price %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Voltar', products_path %>

app/views/welcome/index.html.erb
<h1>Bem Vindo!</h1>

<ul>
    <li><%= link_to 'Cadastro de Produtos', products_path %></li>
</ul>